apiVersion: v1
kind: Service
metadata:
  name: {{ include "reactapp.fullname" . }}
  labels:
    {{- include "reactapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- range .Values.service.loadbalancerips }}      
  loadBalancerSourceRanges:
  - {{ . }}
{{- end }}     
  selector:
    {{- include "reactapp.selectorLabels" . | nindent 4 }}
