name: Deploy for GKE
on: 
  push:
    branches:
      - develop

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  SA: ${{ secrets.GKE_SERVICE_ACCOUNT }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GKE_SERVICE_ACCOUNT }}   
  RUN_REGION: europe-west1-b
  REPO_NAME: react
  CLUSTER_NAME: my-cluster-1

jobs:
  setup-build-deploy-cloudrun:
    name: "Setup, Build, and Deploy CloudRun- '${{github.ref}}'"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ env.SA }}
        export_default_credentials: true
        project_id: ${{ secrets.GKE_PROJECT_ID }}  

        
    - name: Enable docker auth
      run: |-     
        gcloud --quiet auth configure-docker
        
    - name: Build and tag image
      run: |-
        docker build . --tag "gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA"
        
    - name: Push image to GCR
      run: |-
        docker push gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA     
        
    - name: Install helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
#     - name: Deploy Ingress Controller
#       run: |
#          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --region $RUN_REGION
#          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
#          helm repo update
#          helm upgrade --install nginx-ingress ingress-nginx/ingress-nginx --set controller.publishService.enabled=true
    - name: Deploy to GKE Cluster
      run: |-       
        gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --region $RUN_REGION
        # install/upgrade helm chart
        helm upgrade --install reactapp ./helm/reactapp \
        --set image.repository=gcr.io/$PROJECT_ID/$REPO_NAME \
        --set image.tag=$GITHUB_SHA \
        --set service.type=LoadBalancer \
        --set "service.loadbalancerips={148.64.5.237/32}"
        
