name: Provisioning infrastructure for CloudRun
on: 
  push:
    branches:
      - develop

env:
  PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_ID }}
  SA: ${{ secrets.SERVICE_ACCOUNT}}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}   
  RUN_REGION: europe-west1
  REPO_NAME: react

jobs:
  setup-build-deploy-cloudrun:
    name: "Setup, Build, and Deploy CloudRun- '${{github.ref}}'"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    # Setup gcloud CLI  
#     - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
#       with:
#         version: '290.0.1'
#         service_account_key: ${{ secrets.SERVICE_ACCOUNT}}
#         export_default_credentials: true
#         project_id: ${{ secrets.CLOUD_RUN_PROJECT_ID }}  
    - uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: nodejsapp-314207
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: version
        cli: gsutil        
#     - name: Create tf state bucket    
#       run: |-
#         gsutil ls | grep gs://devbucket11
#         if [ "echo $?" != 0 ];then gsutil mb -p nodejsapp-314207 -l europe-west1 -b on gs://devbucket11;fi
#         env:
#           GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}          
        
#     - name: Enable docker auth
#       run: |-     
#         gcloud --quiet auth configure-docker
        
#     - name: Build and tag image
#       run: |-
#         docker build . --tag "gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA"
        
#     - name: Push image to GCR
#       run: |-
#         docker push gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA     
        

#     # Terraform remote state GCS
#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v1

#     - name: Terraform init
#       id: init
#       run: terraform init 
#       continue-on-error: false
#       working-directory: ./tfscripts/react-cloud-run
#       env:
#         GOOGLE_CREDENTIALS: ${{ secrets.SA }}      
#     - name: Terraform Plan
#       id: plan
#       run: terraform plan
#       continue-on-error: false
#       working-directory: ./tfscripts/react-cloud-run  
#       env:
#         GOOGLE_CREDENTIALS: ${{ secrets.SA }}      
#     - name: Terraform apply
#       id: apply
#       run: terraform apply -var="docker_image=gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA" -auto-approve 
#       continue-on-error: false
#       working-directory: ./tfscripts/react-cloud-run
#       env:
#         GOOGLE_CREDENTIALS: ${{ secrets.SA }}
