name: Provisioning infrastructure for CloudRun
on: 
  push:
    branches:
      - feature-gcr
#   pull_request:
#    branches-ignore:
#       - stage
#       - test
#       - master
#       - prod  

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: europe-west1
  DOCKER_IMAGE: gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

jobs:
  setup-build-deploy-cloudrun:
    name: "Setup, Build, and Deploy CloudRun- '${{github.ref}}'"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    # Setup gcloud CLI  
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCP_GKE_TF_SA_KEY}}
        export_default_credentials: true
        project_id: ${{ secrets.GCP_PROJECT_ID }}   
    - name: Enable docker auth
      run: |-     
        gcloud --quiet auth configure-docker
        
    - name: Build and tag image
      run: |-
        docker build . --tag $DOCKER_IMAGE
        
    - name: Push image to GCR
      run: |-
        docker push $DOCKER_IMAGE          
  
    # Terraform remote state GCS
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Terraform script checkout 
    - name: Terraform repository checkout 
      uses: actions/checkout@v2
      with:
        repository: ingka-group-digital/cweb-mgmt-pilot-project/
        ref: dev
        path: cweb-mgmt-pilot-project
        ssh-key: ${{ secrets.CWEB_MGMT_PILOT_SSH }}
        ssh-strict: false

    - name: Terraform init
      id: init
      run: terraform init
      continue-on-error: false
      working-directory: ./cweb-mgmt-pilot-project/tf-scripts/cweb-pilot-project/cloud-run
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    - name: Terraform Plan
      id: plan
      run: terraform plan
      continue-on-error: false
      working-directory: ./cweb-mgmt-pilot-project/tf-scripts/cweb-pilot-project/cloud-run
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}   
    - name: Terraform apply
      id: apply
      run: terraform apply -var="docker-image=$DOCKER_IMAGE" -auto-approve 
      continue-on-error: false
      working-directory: ./cweb-mgmt-pilot-project/tf-scripts/cweb-pilot-project/cloud-run
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS}} 
